"""Scenario-Conditioned Deterioration Forecasting Component for RoadSentinel Dashboard V2."""

from __future__ import annotations

import streamlit as st
import pandas as pd
import numpy as np
from data_loader import (
    load_goal1_forecasts,
    load_primary_results,
    load_canonical_metrics,
)

SCENARIO_DESCRIPTIONS = {
    "NORMAL": "Baseline ambient traffic and climate conditions.",
    "HEAVY_RAIN": "High precipitation stress accelerating crack water-entry.",
    "HEAVY_TRAFFIC": "Elevated dynamic wheel loading and heavy axle passes.",
    "HIGH_HEAT": "High thermal expansion and asphalt binder softening.",
    "WET_EXPOSURE": "Prolonged standing moisture and high humidity penetration (Dominant degradation scenario).",
}


def render_forecast():
    st.markdown("## Scenario-Conditioned Deterioration Forecasting")
    st.markdown(
        "Evaluate **MODEL-BASED FORECASTS** generated by XGBoost Model V2 trained on FHWA LTPP pavement data. "
        "Simulates 30-day, 60-day, and 90-day severity projections under 5 environmental stress scenarios."
    )

    df_fc = load_goal1_forecasts()
    df_prim = load_primary_results()

    if df_fc.empty:
        st.error("Forecast dataset (goal1_forecasts.csv) not found.")
        return

    # Controls
    c1, c2, c3 = st.columns([2, 2, 2])
    with c1:
        seg_id = st.selectbox("Select Road Segment", ["SEG_001", "SEG_002", "SEG_003", "SEG_004"], index=3, key="fc_seg")
    with c2:
        day_num = st.selectbox("Select Inspection Day", list(range(1, 11)), index=4, key="fc_day", format_func=lambda d: f"Day {d:02d}")
    with c3:
        horizon_val = st.selectbox("Forecast Horizon", [30, 60, 90], index=2, format_func=lambda h: f"{h} Days Ahead")

    # Filter Forecasts
    sub_fc = df_fc[(df_fc["segment_id"] == seg_id) & (df_fc["day"] == day_num) & (df_fc["days_ahead"] == horizon_val)]
    prim_row = df_prim[(df_prim["segment_id"] == seg_id) & (df_prim["day"] == day_num)]

    if sub_fc.empty or prim_row.empty:
        st.warning(f"No forecast records available for {seg_id} Day {day_num:02d} at {horizon_val}d.")
        return

    current_sev = float(prim_row.iloc[0]["current_severity"])

    st.markdown("### MODEL-BASED FORECAST COMPARISON")
    
    # Metrics Cards across Scenarios
    scen_cols = st.columns(5)
    scenarios = ["NORMAL", "HIGH_HEAT", "HEAVY_TRAFFIC", "HEAVY_RAIN", "WET_EXPOSURE"]
    
    for idx, scen in enumerate(scenarios):
        row = sub_fc[sub_fc["scenario"] == scen]
        if not row.empty:
            pred_sev = float(row.iloc[0]["predicted_future_severity"])
            pred_delta = float(row.iloc[0]["predicted_change"])
            with scen_cols[idx]:
                st.markdown(f"""
                <div style="background: #1e293b; padding: 14px; border-radius: 8px; border-top: 4px solid {'#2563eb' if scen == 'WET_EXPOSURE' else '#64748b'}; text-align: center;">
                    <b style="color: {'#60a5fa' if scen == 'WET_EXPOSURE' else '#f8fafc'}; font-size: 13px;">{scen}</b>
                    <div style="font-size: 22px; font-weight: bold; color: #f8fafc; margin: 4px 0;">{pred_sev:.4f}</div>
                    <div style="color: #10b981; font-size: 12px;">Δ +{pred_delta:.4f}</div>
                </div>
                """, unsafe_allow_html=True)

    st.markdown("---")

    # Visual Bar Chart Comparison
    scen_names = sub_fc["scenario"].tolist()
    pred_vals = sub_fc["predicted_future_severity"].tolist()
    delta_vals = sub_fc["predicted_change"].tolist()

    chart_df = pd.DataFrame({
        "Scenario": scen_names,
        "Current Severity": [current_sev] * len(scen_names),
        "Predicted Future Severity": pred_vals,
        "Predicted Delta": delta_vals,
    })

    st.bar_chart(chart_df.set_index("Scenario")[["Current Severity", "Predicted Future Severity"]], use_container_width=True)

    # Scientific Disclaimer
    st.markdown("""
    > [!NOTE]
    > **Scientific Disclaimer**: Forecasts are scenario-conditioned regression outputs generated by XGBoost Model V2 
    > trained on LTPP pavement deterioration records. They represent empirical model projections under simulated 
    > environmental stressors and are **not** deterministic physical pavement engineering predictions (PCI).
    """)
