[pytest]
addopts = -p no:launch_testing -p no:launch_testing_ros -p no:launch_testing_ros_pytest_entrypoint -p no:ament_copyright -p no:ament_mypy -p no:ament_pep257 -p no:ament_lint -p no:ament_xmllint -p no:ament_flake8
testpaths = tests
filterwarnings =
    ignore:xFormers is not available.*:UserWarning
    ignore:`torch.jit.script` is not supported in Python 3.14+.*:DeprecationWarning
    ignore:.*torch.jit.script.*:DeprecationWarning
    ignore:builtin type .* has no __module__ attribute:DeprecationWarning
